export const INCREMENT_COUNTER = "INCREMENT_COUNT";
export const DECREMENT_COUNTER = "DECREMENT_COUNT";
export const COUNTER_ACTION_STARTED = "COUNTER_ACTION_STARTED";
export const COUNTER_ACTION_FINISHED = "COUNTER_ACTION_FINISHED";